Repository BanklessDAO/bounty-board, pull requests merged in 2021-08, with the labels that each got.

#44 Feature/documentation readme update
  README.md
Labels: documentation

#41 add final bounties schema
  mongo/bounties/bboard_final.json
  mongo/bounties/bboard_v1.json
  mongo/bounties/bboard_v2.json
  mongo/bounties/bboard_v3.json
  mongo/bounties/validation.js
  mongo/bounties/validation_final.js
Labels: documentation

#52 Feature/degen integration sync
  docs/CHANGELOG.md
  netlify.toml
  package.json
  packages/react-app/.env.qa
  packages/react-app/package.json
  packages/react-app/src/components/pages/Bounties/Form/index.tsx
  packages/react-app/src/constants/discordInfo.ts
  packages/react-app/src/pages/api/bounties/[id].ts
  packages/react-app/src/utils/DiscordUtils.ts
  packages/react-app/src/utils/ServiceUtils.ts
  yarn.lock
Labels: enhancement, react-web

#57 Feature/allow open bounty edit
  docs/CHANGELOG.md
  packages/react-app/.eslintrc.json
  packages/react-app/src/pages/[id]/edit.tsx
  packages/react-app/src/pages/api/bounties/[id].ts
Labels: enhancement

#51 update readme documentation with ux flow, and updated bot commands.
  README.md
Labels: documentation

#73 Feature/add metadata
  packages/react-app/docs/CHANGELOG.md
  packages/react-app/next-seo.config.ts
  packages/react-app/package.json
  packages/react-app/public/logo.png
  packages/react-app/public/preview.png
  packages/react-app/src/components/global/Header/Logo.tsx
  packages/react-app/src/pages/_document.tsx
Labels: bug

#78 general high-level and bounty status queries
  mongo/bounties/bounty_queries.js
Labels: enhancement

#77 adjust hashID in embed
  packages/react-app/docs/CHANGELOG.md
  packages/react-app/package.json
  packages/react-app/src/utils/DiscordUtils.ts
Labels: bug, enhancement

#82 rename .env files
  netlify.toml
  packages/react-app/.env.prod
  packages/react-app/.env.qa
  packages/react-app/docs/CHANGELOG.md
  packages/react-app/src/pages/api/bounties/[id].ts
  packages/react-app/src/utils/ServiceUtils.ts
Labels: bug
