Repository BanklessDAO/bounty-board, pull requests merged in 2021-09, with the labels that each got.

#80 Feature/filters attempt
  mongo/bounties/init.js
  packages/react-app/docs/CHANGELOG.md
  packages/react-app/package.json
  packages/react-app/src/components/pages/Bounties/BountyAccordion/index.tsx
  packages/react-app/src/components/pages/Bounties/Filters/index.tsx
  packages/react-app/src/components/pages/Bounties/index.tsx
  packages/react-app/src/constants/bountyStatus.ts
  packages/react-app/src/hooks/useDebounce.ts
  packages/react-app/src/pages/api/bounties/index.ts
  packages/react-app/src/styles/customTheme.ts
Labels: enhancement, react-web

#92 feature/migrate-to-vercel
  packages/react-app/.env.prod
  packages/react-app/.env.qa
  packages/react-app/package.json
  packages/react-app/src/pages/api/bounties/[id].ts
  packages/react-app/src/utils/ServiceUtils.ts
Labels: bug

#93 modified top lvl README to include setup
  README.md
Labels: documentation, enhancement
